; PlatformIO config and build options for Simple Mono
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name="SimpleMono"
default_envs = osc_bank_b

[env]
platform = ststm32
board = electrosmith_daisy
framework = arduino
lib_deps = 
	electro-smith/DaisyDuino@^1.6.0
	fortyseveneffects/MIDI Library@^5.0.2
build_flags =
    -D HAL_SDRAM_MODULE_ENABLED  ; for HAL_SDRAM errors
    -D USBD_USE_CDC
    -D USBCON
upload_protocol = dfu

[env:osc_bank_a]
build_flags =
    ${env.build_flags}
    -D OSC_BANK=1

[env:osc_bank_b]
build_flags =
    ${env.build_flags}
    -D OSC_BANK=2

[env:osc_bank_c]
build_flags =
    ${env.build_flags}
    -D OSC_BANK=3
